${CXX:-g++} yes.cpp $CXXFLAGS -O3 -s -Wall -Wextra -Wshadow -Wpedantic -pedantic -Werror -std=c++98 -o out/yes
${STRIP:-strip} $STRIPFLAGS --strip-all \
    -N __gentoo_check_ldflags__ -R .comment \
    -R .GCC.command.line --remove-section=.eh_frame \
    --remove-section=.eh_frame_hdr \
    --remove-section=.eh_frame_hdr --remove-section=.eh_frame_ptr \
    --remove-section=.note.gnu.gold-version \
    --remove-section=.note.gnu.build-id \
    --remove-section=.note.ABI-tag --remove-section=.note \
    --remove-section=.gnu.version --remove-section=.comment \
    --remove-section=.note.gnu.property \
    --merge-notes --strip-debug --strip-unneeded -x out/yes
