${AC:-nasm} $AFLAGS -felf64 -O3 -s false.asm
${LD:-ld} $LDFLAGS -O3 -X -s -S -o out/false false.o
${STRIP:-strip} $STRIPFLAGS --strip-all \
    -N __gentoo_check_ldflags__ -R .comment \
    -R .GCC.command.line --remove-section=.eh_frame \
    --remove-section=.eh_frame_hdr --remove-section=.gnu.hash \
    --remove-section=.eh_frame_hdr --remove-section=.eh_frame_ptr \
    --remove-section=.note.gnu.gold-version \
    --remove-section=.note.gnu.build-id \
    --remove-section=.note.ABI-tag --remove-section=.note \
    --remove-section=.gnu.version --remove-section=.comment \
    --merge-notes --strip-debug --strip-unneeded -x out/false
rm false.o
